"""CDP post-processing helpers for query outputs."""

from __future__ import annotations

from .consistency import (
    HistogramPostprocessResult,
    clip_bounds,
    clip_bounds_scalar,
    clip_count,
    clip_non_negative,
    clip_non_negative_scalar,
    clip_probability,
    clip_sum,
    clip_variance,
    enforce_monotonic,
    normalize_probabilities,
    postprocess_count,
    postprocess_histogram,
    postprocess_mean,
    postprocess_rate,
    postprocess_sum,
    postprocess_variance,
    project_simplex,
    rescale_to_total,
    safe_divide,
    safe_mean,
    safe_rate,
    variance_upper_bound,
)

__all__ = [
    "HistogramPostprocessResult",
    "clip_bounds",
    "clip_bounds_scalar",
    "clip_count",
    "clip_non_negative",
    "clip_non_negative_scalar",
    "clip_probability",
    "clip_sum",
    "clip_variance",
    "enforce_monotonic",
    "normalize_probabilities",
    "postprocess_count",
    "postprocess_histogram",
    "postprocess_mean",
    "postprocess_rate",
    "postprocess_sum",
    "postprocess_variance",
    "project_simplex",
    "rescale_to_total",
    "safe_divide",
    "safe_mean",
    "safe_rate",
    "variance_upper_bound",
]
