"""CDP module entrypoint aggregating analytics, mechanisms, composition, and sensitivity."""

from __future__ import annotations

# Analytics (queries, reporting, synthetic data)
from .analytics import (
    BayesianNetworkGenerator,
    CopulaGenerator,
    DPSyntheticGAN,
    ErrorMetrics,
    MarginalGenerator,
    PrivacyAnnotation,
    PrivacyBudgetSnapshot,
    PrivacyReport,
    PrivacyUsageRecord,
    PrivateCountQuery,
    PrivateHistogramQuery,
    PrivateMeanQuery,
    PrivateRangeQuery,
    PrivateSumQuery,
    PrivateVarianceQuery,
    QueryEngine,
    QueryUtilityRecord,
    SyntheticDataGenerator,
    SyntheticGeneratorConfig,
    UtilityCurve,
    UtilityReport,
    create_generator,
)

# Mechanisms
from .mechanisms import (
    ExponentialMechanism,
    GaussianMechanism,
    GeometricMechanism,
    LaplaceMechanism,
    StaircaseMechanism,
    VectorMechanism,
    MECHANISM_REGISTRY,
    create_mechanism,
    ensure_mechanism_supports_model,
    get_mechanism_class,
    normalize_mechanism,
    registered_mechanisms_snapshot,
)

# Composition
from .composition import (
    AccountingMethod,
    Allocation,
    AdvancedCompositionRule,
    BudgetScheduler,
    CDPPrivacyAccountant,
    MomentAccountant,
    RhoZCDPCompositionRule,
    advanced_composition,
    advanced_pure_dp_bound,
    assert_non_decreasing_spending,
    compare_composition_paths,
    drv10_strong_bound,
    gdp_composition,
    gdp_to_cdp_bound,
    group_privacy,
    linear_addition,
    optimal_composition_fallback,
    parallel_composition,
    parallel_max,
    post_processing_invariance,
    rdp_composition,
    rdp_to_cdp_bound,
    repeated_mechanism,
    rho_zcdp_composition,
    sequential_composition,
    sequential_sum,
    shuffle_amplification,
    strong_composition,
    subsampling_amplification,
    zcdp_to_cdp_bound,
)

# Sensitivity
from .sensitivity import (
    GLOBAL_SENSITIVITY_PRESETS,
    SensitivityAnalyzer,
    SensitivityBounds,
    SensitivityError,
    SensitivityReport,
    calibrate,
    calibrate_gaussian,
    calibrate_laplace,
    count,
    count_bounds,
    histogram,
    histogram_bounds,
    mean,
    mean_bounds,
    range,
    range_bounds,
    sum,
    sum_bounds,
    tighten,
    variance,
    variance_bounds,
)

__all__ = [
    # Analytics - queries
    "PrivateCountQuery",
    "PrivateHistogramQuery",
    "PrivateMeanQuery",
    "PrivateRangeQuery",
    "PrivateSumQuery",
    "PrivateVarianceQuery",
    "QueryEngine",
    # Analytics - reporting
    "PrivacyAnnotation",
    "PrivacyBudgetSnapshot",
    "PrivacyReport",
    "PrivacyUsageRecord",
    "ErrorMetrics",
    "QueryUtilityRecord",
    "UtilityCurve",
    "UtilityReport",
    # Analytics - synthetic data
    "SyntheticGeneratorConfig",
    "SyntheticDataGenerator",
    "create_generator",
    "MarginalGenerator",
    "BayesianNetworkGenerator",
    "DPSyntheticGAN",
    "CopulaGenerator",
    # Mechanisms
    "LaplaceMechanism",
    "GaussianMechanism",
    "ExponentialMechanism",
    "GeometricMechanism",
    "StaircaseMechanism",
    "VectorMechanism",
    "MECHANISM_REGISTRY",
    "normalize_mechanism",
    "get_mechanism_class",
    "ensure_mechanism_supports_model",
    "registered_mechanisms_snapshot",
    "create_mechanism",
    # Composition
    "group_privacy",
    "linear_addition",
    "parallel_composition",
    "post_processing_invariance",
    "repeated_mechanism",
    "sequential_composition",
    "AdvancedCompositionRule",
    "RhoZCDPCompositionRule",
    "advanced_composition",
    "gdp_composition",
    "optimal_composition_fallback",
    "rho_zcdp_composition",
    "rdp_composition",
    "shuffle_amplification",
    "strong_composition",
    "subsampling_amplification",
    "advanced_pure_dp_bound",
    "assert_non_decreasing_spending",
    "compare_composition_paths",
    "drv10_strong_bound",
    "gdp_to_cdp_bound",
    "parallel_max",
    "rdp_to_cdp_bound",
    "sequential_sum",
    "zcdp_to_cdp_bound",
    "AccountingMethod",
    "CDPPrivacyAccountant",
    "Allocation",
    "BudgetScheduler",
    "MomentAccountant",
    # Sensitivity
    "SensitivityError",
    "SensitivityAnalyzer",
    "SensitivityReport",
    "calibrate",
    "calibrate_gaussian",
    "calibrate_laplace",
    "SensitivityBounds",
    "count_bounds",
    "histogram_bounds",
    "mean_bounds",
    "range_bounds",
    "sum_bounds",
    "tighten",
    "variance_bounds",
    "GLOBAL_SENSITIVITY_PRESETS",
    "count",
    "histogram",
    "mean",
    "range",
    "sum",
    "variance",
]
