"""Entry point for CDP analytics components."""

from __future__ import annotations

from .queries import (
    PrivateCountQuery,
    PrivateHistogramQuery,
    PrivateMeanQuery,
    PrivateRangeQuery,
    PrivateSumQuery,
    PrivateVarianceQuery,
    QueryEngine,
)
from .reporting import (
    ErrorMetrics,
    PrivacyAnnotation,
    PrivacyBudgetSnapshot,
    PrivacyReport,
    PrivacyUsageRecord,
    QueryUtilityRecord,
    UtilityCurve,
    UtilityReport,
)
from .postprocessing import (
    HistogramPostprocessResult,
    clip_bounds,
    clip_bounds_scalar,
    clip_count,
    clip_non_negative,
    clip_non_negative_scalar,
    clip_probability,
    clip_sum,
    clip_variance,
    enforce_monotonic,
    normalize_probabilities,
    postprocess_count,
    postprocess_histogram,
    postprocess_mean,
    postprocess_rate,
    postprocess_sum,
    postprocess_variance,
    project_simplex,
    rescale_to_total,
    safe_divide,
    safe_mean,
    safe_rate,
    variance_upper_bound,
)
from .synthetic_data import (
    BayesianNetworkGenerator,
    CopulaGenerator,
    DPSyntheticGAN,
    MarginalGenerator,
    SyntheticDataGenerator,
    SyntheticGeneratorConfig,
    create_generator,
)

__all__ = [
    # Queries
    "PrivateCountQuery",
    "PrivateHistogramQuery",
    "PrivateMeanQuery",
    "PrivateRangeQuery",
    "PrivateSumQuery",
    "PrivateVarianceQuery",
    "QueryEngine",
    # Reporting
    "PrivacyAnnotation",
    "PrivacyBudgetSnapshot",
    "PrivacyReport",
    "PrivacyUsageRecord",
    "ErrorMetrics",
    "QueryUtilityRecord",
    "UtilityCurve",
    "UtilityReport",
    # Postprocessing
    "HistogramPostprocessResult",
    "clip_bounds",
    "clip_bounds_scalar",
    "clip_count",
    "clip_non_negative",
    "clip_non_negative_scalar",
    "clip_probability",
    "clip_sum",
    "clip_variance",
    "enforce_monotonic",
    "normalize_probabilities",
    "postprocess_count",
    "postprocess_histogram",
    "postprocess_mean",
    "postprocess_rate",
    "postprocess_sum",
    "postprocess_variance",
    "project_simplex",
    "rescale_to_total",
    "safe_divide",
    "safe_mean",
    "safe_rate",
    "variance_upper_bound",
    # Synthetic data
    "SyntheticGeneratorConfig",
    "SyntheticDataGenerator",
    "create_generator",
    "MarginalGenerator",
    "BayesianNetworkGenerator",
    "DPSyntheticGAN",
    "CopulaGenerator",
]
